=== openembedded/bitbake/setup-schema/bitbake-setup.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "Schema for bitbake-setup configuration files",
    "title": "bitbake-setup configuration file",
    "type": "object",
    "required": [
        "description",
        "bitbake-setup",
        "version"
    ],
    "properties": {
        "description": {
            "type": "string",
            "description": "Description of the bitbake-setup configuration file"
        },
        "sources": {
            "$ref": "layers.schema.json#/properties/sources"
        },
        "expires": {
            "type": "string",
            "description": "End of life date for this configuration, in ISO 8601 format (YYYY-MM-DD)"
        },
        "bitbake-setup": {
            "type": "object",
            "description": "BitBake-setup configurations",
            "required": [
                "configurations"
            ],
            "properties": {
                "configurations": {
                    "type": "array",
                    "minItems": 1,
                    "$anchor": "configurations",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Name of the configuration"
                            },
                            "description": {
                                "type": "string",
                                "description": "Human-readable description of the configuration"
                            },
                            "notes": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                ],
                                "description": "Extra notes that populate conf-notes.txt when bb-layers is used"
                            },
                            "bb-layers": {
                                "type": "array",
                                "description": "List of BitBake layer paths to include, relative to the layers download directory",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "bb-layers-file-relative": {
                                "type": "array",
                                "description": "List of BitBake layers paths to include, relative to the directory with the configuration file",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "oe-template": {
                                "type": "string",
                                "description": "OE-template configuration"
                            },
                            "oe-fragments": {
                                "$anchor": "oe-fragments",
                                "type": "array",
                                "description": "List of BitBake configuration fragments to enable",
                                "items": {
                                    "oneOf": [
                                        {
                                            "type": "string",
                                            "description": "Configuration fragment name"
                                        },
                                        {
                                            "type": "object",
                                            "description": "Dictionary of BitBake configuration fragments to enable (with description)",
                                            "properties": {
                                                "name": {
                                                    "type": "string",
                                                    "description": "Configuration fragment name"
                                                },
                                                "description": {
                                                    "type": "string",
                                                    "description": "Human-readable description of the fragment"
                                                }
                                            }
                                        }
                                    ]
                                }
                            },
                            "oe-fragments-one-of": {
                                "type": "object",
                                "description": "Mutually exclusive bitbake configuration fragment",
                                "patternProperties": {
                                    ".*": {
                                        "type": "object",
                                        "required": [
                                            "description",
                                            "options"
                                        ],
                                        "properties": {
                                            "description": {
                                                "type": "string",
                                                "description": "Human-readable description of the fragment category"
                                            },
                                            "options": {
                                                "$ref": "#oe-fragments"
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                },
                                "additionalProperties": false
                            },
                            "configurations": {
                                "$ref": "#configurations"
                            },
                            "bb-env-passthrough-additions": {
                                "type": "array",
                                "description": "List of environment variables to include in BB_ENV_PASSTHROUGH_ADDITIONS",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "setup-dir-name": {
                                "type": "string",
                                "description": "A suggestion for the setup directory name, $-prefixed keys from oe-fragments-one-of will be substituted with user selections."
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        },
        "version": {
            "description": "The version of this document; currently '1.0'",
            "enum": [
                "1.0"
            ]
        }
    },
    "additionalProperties": false
}

=== openembedded/bitbake/default-registry/configurations/oe-nodistro.conf.json
{
    "description": "OpenEmbedded - 'nodistro' basic configuration",
    "sources": {
        "bitbake": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.openembedded.org/bitbake;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            }
        },
        "openembedded-core": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.openembedded.org/openembedded-core;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            }
        },
        "yocto-docs": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.yoctoproject.org/yocto-docs;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            }
        }
    },
    "bitbake-setup": {
        "configurations": [
        {
            "name": "nodistro",
            "description": "OpenEmbedded 'nodistro'",
            "bb-layers": ["openembedded-core/meta"],
            "oe-fragments-one-of": {
                "machine": {
                    "description": "Target machines",
                    "options" : ["machine/qemux86-64", "machine/qemuarm64", "machine/qemuriscv64"]
                }
            }
        }
        ]
    },
    "version": "1.0"
}

=== openembedded/bitbake/default-registry/configurations/poky-master.conf.json
{
    "description": "Poky - The Yocto Project testing distribution configurations and hardware test platforms",
    "sources": {
        "bitbake": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.openembedded.org/bitbake;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            }
        },
        "openembedded-core": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.openembedded.org/openembedded-core;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            }
        },
        "meta-yocto": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.yoctoproject.org/meta-yocto;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            }
        },
        "yocto-docs": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.yoctoproject.org/yocto-docs;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            }
        }
    },
    "bitbake-setup": {
        "configurations": [
        {
            "bb-layers": ["openembedded-core/meta","meta-yocto/meta-yocto-bsp","meta-yocto/meta-poky"],
            "setup-dir-name": "$distro-master",
            "oe-fragments-one-of": {
                "machine": {
                    "description": "Target machines",
                    "options" : ["machine/qemux86-64", "machine/qemuarm64", "machine/qemuriscv64", "machine/genericarm64", "machine/genericx86-64"]
                },
                "distro": {
                    "description": "Distribution configuration variants",
                    "options" : ["distro/poky", "distro/poky-altcfg", "distro/poky-tiny"]
                }
            },
            "configurations": [
            {
                "name": "poky",
                "description": "Poky - The Yocto Project testing distribution"
            },
            {
                "name": "poky-with-sstate",
                "description": "Poky - The Yocto Project testing distribution with internet sstate acceleration. Use with caution as it requires a completely robust local network with sufficient bandwidth.",
                "oe-fragments": ["core/yocto/sstate-mirror-cdn"]
            }
            ]
        }
        ]
    },
    "version": "1.0"
}

=== openembedded/bitbake/default-registry/configurations/oe-nodistro-whinlatter.conf.json
{
    "description": "OpenEmbedded - 'nodistro' basic configuration, release 5.3 'whinlatter'",
    "expires": "2026-05-31",
    "sources": {
        "bitbake": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "https://git.openembedded.org/bitbake"
                    }
                },
                "branch": "2.16",
                "rev": "2.16"
            }
        },
        "openembedded-core": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "https://git.openembedded.org/openembedded-core"
                    }
                },
                "branch": "whinlatter",
                "rev": "whinlatter"
            }
        },
        "yocto-docs": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "https://git.yoctoproject.org/yocto-docs"
                    }
                },
                "branch": "whinlatter",
                "rev": "whinlatter"
            }
        }
    },
    "bitbake-setup": {
        "configurations": [
        {
            "name": "nodistro",
            "description": "OpenEmbedded 'nodistro'",
            "setup-dir-name": "oe-nodistro-whinlatter",
            "bb-layers": ["openembedded-core/meta"],
            "oe-fragments-one-of": {
                "machine": {
                    "description": "Target machines",
                    "options" : ["machine/qemux86-64", "machine/qemuarm64", "machine/qemuriscv64"]
                }
            }
        }
        ]
    },
    "version": "1.0"
}

=== openembedded/bitbake/default-registry/configurations/oe-nodistro-master.conf.json
{
    "description": "OpenEmbedded - 'nodistro' basic configuration",
    "sources": {
        "bitbake": {
            "git-remote": {
                "uri": "https://git.openembedded.org/bitbake",
                "branch": "master",
                "rev": "master"
            }
        },
        "openembedded-core": {
            "git-remote": {
                "uri": "https://git.openembedded.org/openembedded-core",
                "branch": "master",
                "rev": "master"
            }
        },
        "yocto-docs": {
            "git-remote": {
                "uri": "https://git.yoctoproject.org/yocto-docs",
                "branch": "master",
                "rev": "master"
            }
        }
    },
    "bitbake-setup": {
        "configurations": [
        {
            "name": "nodistro",
            "description": "OpenEmbedded 'nodistro'",
            "setup-dir-name": "oe-nodistro-master",
            "bb-layers": ["openembedded-core/meta"],
            "oe-fragments-one-of": {
                "machine": {
                    "description": "Target machines",
                    "options" : ["machine/qemux86-64", "machine/qemuarm64", "machine/qemuriscv64"]
                }
            }
        }
        ]
    },
    "version": "1.0"
}

=== openembedded/bitbake/default-registry/configurations/poky-whinlatter.conf.json
{
    "description": "Poky - The Yocto Project testing distribution configurations and hardware test platforms, release 5.3 'whinlatter'",
    "expires": "2026-05-31",
    "sources": {
        "bitbake": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "https://git.openembedded.org/bitbake"
                    }
                },
                "branch": "2.16",
                "rev": "2.16"
            }
        },
        "openembedded-core": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "https://git.openembedded.org/openembedded-core"
                    }
                },
                "branch": "whinlatter",
                "rev": "whinlatter"
            }
        },
        "meta-yocto": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "https://git.yoctoproject.org/meta-yocto"
                    }
                },
                "branch": "whinlatter",
                "rev": "whinlatter"
            }
        },
        "yocto-docs": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "https://git.yoctoproject.org/yocto-docs"
                    }
                },
                "branch": "whinlatter",
                "rev": "whinlatter"
            }
        }
    },
    "bitbake-setup": {
        "configurations": [
        {
            "bb-layers": ["openembedded-core/meta","meta-yocto/meta-yocto-bsp","meta-yocto/meta-poky"],
            "setup-dir-name": "$distro-whinlatter",
            "oe-fragments-one-of": {
                "machine": {
                    "description": "Target machines",
                    "options" : ["machine/qemux86-64", "machine/qemuarm64", "machine/qemuriscv64", "machine/genericarm64", "machine/genericx86-64"]
                },
                "distro": {
                    "description": "Target Distributions",
                    "options" : ["distro/poky", "distro/poky-altcfg", "distro/poky-tiny"]
                }
            },
            "configurations": [
            {
                "name": "poky",
                "description": "Poky - The Yocto Project testing distribution"
            },
            {
                "name": "poky-with-sstate",
                "description": "Poky - The Yocto Project testing distribution with internet sstate acceleration. Use with caution as it requires a completely robust local network with sufficient bandwidth.",
                "oe-fragments": ["core/yocto/sstate-mirror-cdn"]
            }
            ]
        }
        ]
    },
    "version": "1.0"
}

=== openembedded/bitbake/default-registry/configurations/oe-nodistro-wrynose.conf.json
{
    "description": "OpenEmbedded - 'nodistro' basic configuration, release 6.0 'wrynose'",
    "expires": "2030-05-31",
    "sources": {
        "bitbake": {
            "git-remote": {
                "uri": "https://git.openembedded.org/bitbake",
                "branch": "2.18",
                "rev": "2.18"
            }
        },
        "openembedded-core": {
            "git-remote": {
                "uri": "https://git.openembedded.org/openembedded-core",
                "branch": "wrynose",
                "rev": "wrynose"
            }
        },
        "yocto-docs": {
            "git-remote": {
                "uri": "https://git.yoctoproject.org/yocto-docs",
                "branch": "wrynose",
                "rev": "wrynose"
            }
        }
    },
    "bitbake-setup": {
        "configurations": [
        {
            "name": "nodistro",
            "description": "OpenEmbedded 'nodistro'",
            "setup-dir-name": "oe-nodistro-wrynose",
            "bb-layers": ["openembedded-core/meta"],
            "oe-fragments-one-of": {
                "machine": {
                    "description": "Target machines",
                    "options" : [
                        { "name": "machine/qemux86-64", "description": "x86-64 system on QEMU" },
                        { "name": "machine/qemuarm64", "description": "ARMv8 system on QEMU" },
                        { "name": "machine/qemuriscv64", "description": "RISC-V system on QEMU" }
                    ]
                }
            }
        }
        ]
    },
    "version": "1.0"
}
